#!/bin/bash
# Quick reference for running the prediction API correctly

echo "Magic8 Prediction API - Quick Start"
echo "==================================="
echo ""
echo "From project root directory:"
echo ""
echo "1. With pre-flight checks (recommended):"
echo "   ./start_api_with_checks.py"
echo ""
echo "2. Simple runner:"
echo "   ./run_prediction_api.py"
echo ""
echo "3. Direct module execution:"
echo "   python -m src.prediction_api"
echo ""
echo "4. With explicit PYTHONPATH:"
echo "   PYTHONPATH=. python -m src.prediction_api"
echo ""
echo "DO NOT run directly with:"
echo "   ❌ python src/prediction_api.py  (will fail with import errors)"
echo ""
echo "API will be available at: http://localhost:8000"
echo "API docs at: http://localhost:8000/docs"
