# Magic8 Accuracy Predictor Configuration - Test/Development

system:
  environment: "development"
  log_level: "INFO"

# Data source configuration - using mock provider for testing
data_source:
  primary: "mock"  # Use mock provider for testing without external dependencies
  
  mock:
    enabled: true
    # Mock provider doesn't need configuration
    
  companion:
    enabled: false
    base_url: "http://localhost:8765"
    timeout: 5
    retry_attempts: 3
    
  redis:
    enabled: false
    host: "localhost"
    port: 6379
    db: 0
    
  standalone:
    enabled: false
    ib_host: "127.0.0.1"
    ib_port: 7498
    client_id: 99

# Prediction configuration
prediction:
  models:
    - name: "xgboost_phase1"
      path: "models/phase1/xgboost_model.pkl"
      symbols: ["SPX", "SPY", "RUT", "QQQ", "XSP", "NDX", "AAPL", "TSLA"]
      version: "1.0.0"
    
  feature_config:
    temporal:
      enabled: true
      features: ["hour", "minute", "day_of_week", "minutes_to_close"]
      
    price:
      enabled: true
      sma_periods: [20]
      momentum_periods: [5]
      rsi_period: 14
      
    vix:
      enabled: true
      sma_period: 20
      regime_thresholds: [15, 20, 25]

# Integration settings
integration:
  discord_trading:
    enabled: true
    min_win_probability: 0.55
    skip_on_error: false
    log_all_predictions: true
    
  monitoring:
    enabled: true
    track_predictions: true
    save_to_file: true
    predictions_file: "logs/predictions.jsonl"

# Performance optimization
performance:
  cache:
    enabled: true
    ttl_seconds: 300
    max_size: 1000
